# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "#home"
#  weight = 10

[[main]]
  name = "Research themes"
  url = "#projects"
  weight = 10
  
[[main]]
  name = "Publications"
  url = "#publications"
  identifier = "pubs"
  weight = 20
  
[[main]]
  name = "Published/Accepted"
  url = "#publications"
  parent = "pubs"
  weight = 20

[[main]]
  name = "Preprints"
  url = "#preprints"
  parent = "pubs"
  weight = 20
  
[[main]]
  name = "Talks"
  url = "#talks"
  weight = 30

[[main]]
  name = "Software"
  url = "#software"
  weight = 40

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 50

[[main]]
  name = "Podcasts"
  url = "#podcasts"
  weight = 55

[[main]]
  name = "People"
  url = "people/"
  weight = 60

[[main]]
  name = "Teaching"
  url = "courses/"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
